#!/usr/bin/env node
import { Command } from 'commander';
import chalk from 'chalk';
import fs from 'fs';
import path from 'path';
import { config, doctorReport } from './config.js';
import { loadPolicy, evaluate } from './policy.js';
import { appendAudit, readRecent } from './audit.js';
import { checkBudgets, loadState } from './state.js';
import { ActionSchema, type Action } from './types.js';

const program = new Command();

program
  .name('gibwork-gateway')
  .description('Enterprise MCP Control Plane for Gibwork')
  .version('1.0.0');

const KNOWN_ACTIONS = ActionSchema.options;

program
  .command('doctor')
  .description('Diagnose gateway configuration and policy')
  .option('--json', 'Machine-readable output')
  .action((opts) => {
    const lines = doctorReport();
    let policyName = 'unloaded';
    let policyRules = 0;
    let policyError: string | null = null;
    try {
      const p = loadPolicy();
      policyName = p.name;
      policyRules = p.rules.length;
    } catch (e: any) {
      policyError = e.message;
    }

    if (opts.json) {
      console.log(JSON.stringify({
        gateway: `${config.gatewayName}@${config.gatewayVersion}`,
        environment: config.gibworkEnvironment,
        dryRun: config.dryRun,
        walletPresent: !!config.solanaPrivateKey,
        policyFile: config.policyFile,
        policyName,
        policyRules,
        policyError,
        auditDir: config.auditDir,
        budgets: {
          dailySpendLimit: config.dailySpendLimit,
          maxTasksPerDay: config.maxTasksPerDay,
          maxSubmissionsPerDay: config.maxSubmissionsPerDay,
        },
      }, null, 2));
      return;
    }

    console.log(chalk.bold.blue('\nGibwork MCP Gateway — Doctor\n'));
    lines.forEach(l => console.log('  ' + l));
    if (policyError) {
      console.log(chalk.red(`\n  Policy error  : ${policyError}`));
    } else {
      console.log(chalk.green(`\n  Policy loaded : ${policyName} (${policyRules} rules)`));
    }
    console.log();
  });

program
  .command('actions')
  .description('List supported policy actions')
  .option('--json', 'Machine-readable output')
  .action((opts) => {
    if (opts.json) {
      console.log(JSON.stringify(KNOWN_ACTIONS, null, 2));
      return;
    }
    console.log(chalk.bold.blue('\nSupported Actions\n'));
    KNOWN_ACTIONS.forEach(a => console.log(`  • ${a}`));
    console.log();
  });

program
  .command('init')
  .description('Scaffold a policy file (does not overwrite existing)')
  .option('--file <path>', 'Target policy path', config.policyFile)
  .option('--force', 'Overwrite if exists')
  .action((opts) => {
    const target = path.resolve(opts.file);
    if (fs.existsSync(target) && !opts.force) {
      console.log(chalk.yellow(`Policy already exists: ${target}`));
      console.log('Use --force to overwrite.');
      process.exit(1);
    }
    const dir = path.dirname(target);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    const template = `name: custom-policy
description: Generated by gibwork-gateway init
defaultEffect: deny
rules:
  - action: tasks.list
    effect: allow
  - action: tasks.get
    effect: allow
  - action: submissions.list
    effect: allow
  - action: wallet.read
    effect: allow
  - action: proof.run
    effect: allow
  - action: tasks.create
    effect: allow
    conditions:
      environment: [stage]
      maxAmount: 50
  - action: submissions.create
    effect: allow
    conditions:
      environment: [stage]
  - action: proof.submit
    effect: allow
    conditions:
      environment: [stage]
  - action: submissions.approve
    effect: deny
  - action: tasks.refund
    effect: deny
budgets:
  dailySpendLimit: 100
  maxTasksPerDay: 25
  maxSubmissionsPerDay: 50
`;
    fs.writeFileSync(target, template);
    console.log(chalk.green(`✓ Policy written: ${target}`));
  });

program
  .command('policy')
  .description('Show the active policy')
  .option('--file <path>', 'Policy file override')
  .action((opts) => {
    console.log(JSON.stringify(loadPolicy(opts.file), null, 2));
  });

program
  .command('check')
  .description('Evaluate whether an action is allowed under the policy')
  .requiredOption('--action <action>', 'Action name (e.g. tasks.create)')
  .option('--amount <n>', 'Amount involved', parseFloat)
  .option('--tags <tags>', 'Comma-separated tags')
  .option('--json', 'Machine-readable output')
  .action((opts) => {
    if (!KNOWN_ACTIONS.includes(opts.action) && opts.action !== '*') {
      const msg = `Unknown action "${opts.action}". Use "gibwork-gateway actions" to list valid actions.`;
      if (opts.json) console.log(JSON.stringify({ error: msg, allowed: false }));
      else console.error(chalk.red(msg));
      process.exit(1);
    }

    const policy = loadPolicy();
    const decision = evaluate(policy, opts.action as Action, {
      amount: opts.amount,
      tags: opts.tags ? opts.tags.split(',').map((t: string) => t.trim()) : undefined,
    });
    const budget = checkBudgets(policy.budgets);
    const allowed = decision.allowed && budget.ok;

    appendAudit({
      action: opts.action,
      effect: allowed ? 'allow' : 'deny',
      amount: opts.amount,
      reason: decision.reason,
    });

    if (opts.json) {
      console.log(JSON.stringify({
        action: opts.action,
        allowed,
        decision,
        budgets: {
          spend: `${budget.state.spendToday}/${budget.spendLimit}`,
          tasks: `${budget.state.tasksCreatedToday}/${budget.taskLimit}`,
          submissions: `${budget.state.submissionsToday}/${budget.subLimit}`,
          ok: budget.ok,
        },
      }, null, 2));
    } else {
      console.log(chalk.bold.blue('\nPolicy Check\n'));
      console.log(`Action   : ${opts.action}`);
      console.log(`Allowed  : ${allowed ? chalk.green('yes') : chalk.red('no')}`);
      console.log(`Reason   : ${decision.reason}`);
      if (decision.matchedRule) console.log(`Rule     : ${decision.matchedRule}`);
      console.log(`\nBudgets  : spend=${budget.state.spendToday}/${budget.spendLimit}  tasks=${budget.state.tasksCreatedToday}/${budget.taskLimit}  subs=${budget.state.submissionsToday}/${budget.subLimit}`);
      console.log(`Budget OK: ${budget.ok ? chalk.green('yes') : chalk.red('no')}`);
    }

    process.exit(allowed ? 0 : 1);
  });

program
  .command('audit')
  .description('Show recent audit events')
  .option('--limit <n>', 'Max events', '30')
  .option('--json', 'Machine-readable output')
  .action((opts) => {
    const events = readRecent(Number(opts.limit));
    if (opts.json) {
      console.log(JSON.stringify(events, null, 2));
      return;
    }
    console.log(chalk.bold.blue('\nAudit Log\n'));
    if (!events.length) {
      console.log('  (empty)');
      return;
    }
    events.forEach(e => {
      const mark = e.effect === 'allow' || e.effect === 'executed' ? chalk.green(e.effect) : chalk.red(e.effect);
      console.log(`  ${e.ts}  ${mark}  ${e.action}  ${e.reason || ''}`);
    });
    console.log();
  });

program
  .command('status')
  .description('Show gateway state and budgets')
  .option('--json', 'Machine-readable output')
  .action((opts) => {
    const state = loadState();
    const policy = loadPolicy();
    const budget = checkBudgets(policy.budgets);

    if (opts.json) {
      console.log(JSON.stringify({
        day: state.dayKey,
        spendToday: state.spendToday,
        spendLimit: budget.spendLimit,
        tasksCreatedToday: state.tasksCreatedToday,
        taskLimit: budget.taskLimit,
        submissionsToday: state.submissionsToday,
        subLimit: budget.subLimit,
        policy: policy.name,
        environment: config.gibworkEnvironment,
        dryRun: config.dryRun,
      }, null, 2));
      return;
    }

    console.log(chalk.bold.blue('\nGateway Status\n'));
    console.log(`Day              : ${state.dayKey}`);
    console.log(`Spend today      : ${state.spendToday} / ${budget.spendLimit}`);
    console.log(`Tasks created    : ${state.tasksCreatedToday} / ${budget.taskLimit}`);
    console.log(`Submissions      : ${state.submissionsToday} / ${budget.subLimit}`);
    console.log(`Policy           : ${policy.name}`);
    console.log(`Environment      : ${config.gibworkEnvironment}`);
    console.log(`Dry-run          : ${config.dryRun}`);
    console.log();
  });

program.parse();
